### ISSUE TITLE
Update failed: KeyError('Channel2HrForecast')

### ISSUE THREAD

**Issue by MoonshineSG** [liangleslie/nea_sg_weather#2]
As per title, this is the error I get after activating the integration. Runs the config fine, but then this error shows.

**Comment by MoonshineSG** [comment]
timeout on https://www.nea.gov.sg/api/WeatherForecast/forecast24hrnowcast2hrs/1647311672 request

**Comment by MoonshineSG** [comment]
seams like the issue was with the api, and it has been restored.

**Comment by MoonshineSG** [comment]
Seams like a lot of timeouts and unavailable APi.... not sure who's fault is it.. but leave this open in case someone is fixing anything..

**Comment by coffeepotatochips** [comment]
Is this related to the issue where weather forecast does not change unless HA is reset (which causes it to refresh the sensor value)?

**Comment by liangleslie** [comment]
KeyError happens when the API call returns data that is incomplete and Python is unable to parse the response to extract the values needed to update the sensor. It really shouldn't happen and even if it does, it would be a server side error that I won't be able to fix.

I haven't seen any such errors recently on my end, so I will close this issue.

As for the weather forecast (separate issue from this), I noticed a bug in the code and just released an update to fix it hopefully. Please try v1.3.1 and see if it works
