### ISSUE TITLE
How to change refresh rate?

### ISSUE THREAD

**Issue by TiankaiChen** [liangleslie/nea_sg_weather#21]
Hi, I see the default refresh rate is 15 mins, would it be possible to set the refresh rate to every 5 mins instead? Is there a way to configure it in the UI?

**Comment by liangleslie** [comment]
It is not intended for users to reduce this to anything less than 15 since the APIs are not intended to provide realtime weather updates and the frequent calls may overwhelm the service.

Will not be adding this feature. Power users who knows what they are doing can easily modify the code to achieve this.
