### ISSUE TITLE
API issues

### ISSUE THREAD

**Issue by unxplained** [liangleslie/nea_sg_weather#5]
Hi, 

I think these 2 APIs are down, not sure whether NEA deprecated them.

https://api.data.gov.sg/v1/environment/wind-direction
https://api.data.gov.sg/v1/environment/wind-speed

These “internal server error” causes the entire integration to fail, is it possible to ignore these responses?

Thanks

**Comment by liangleslie** [comment]
Not much I can do, pretty much every weather endpoint is down.

Hard for the data.gov.sg integration to work if data.gov.sg is down.

Sorry guys

**Comment by liangleslie** [comment]
API is back up, closing this issue

**Comment by s0ftice** [comment]
and offline again... 
I dropped an email to feedback@data.gov.sg, let's see.
(Your request has been received and is being reviewed by our support staff.)

I will update here in case they provide an explanation.

thanks for your integration Leslie, been using it for quite some time!

**Comment by s0ftice** [comment]
Thanks for that, I'll give it a try when it happens again.

By the way, they got back to me saying "Apologies the NEA API was down. We have since fixed the issue, and it should work now. Do try it out."

I also asked them what's the best way of reaching out when this happens again, via feedback@data.gov.sg as I did, or if there's a direct way of contacting NEA (as they are only one of many contributors to the overall api.data.gov.sg initiative, and only their API seems to have these issues lately).
They responded saying "You may write in to data.gov.sg".

Regards
